// Copyright (c) James Jackson-South.
// See LICENSE for more details.

// <auto-generated />

namespace FileSystem.Abstractions
{
    public static class Constants
    {
        /// <summary>
        /// Defines well-known entity types.
        /// </summary>
        /// <remarks>
        /// Well-known entity types are those that Deploy already knows about,
        /// but entity types are strings and so can be extended beyond what is defined here.
        /// </remarks>
        public static class UdiEntityTypes
        {
            // GUID
            // TODO: We should Unknown be a thing? we will always have a type now.
            public static UdiEntityType Unknown = new UdiEntityType(UdiType.ClosedGuid, "unknown");
            public static UdiEntityType Element = new UdiEntityType(UdiType.ClosedGuid, "element");
            public static UdiEntityType Document = new UdiEntityType(UdiType.ClosedGuid, "document");
            public static UdiEntityType DocumentBlueprint = new UdiEntityType(UdiType.ClosedGuid, "document-blueprint");
            public static UdiEntityType Media = new UdiEntityType(UdiType.ClosedGuid, "media");
            public static UdiEntityType Member = new UdiEntityType(UdiType.ClosedGuid, "member");
            public static UdiEntityType DictionaryItem = new UdiEntityType(UdiType.ClosedGuid, "dictionary-item");
            public static UdiEntityType Macro = new UdiEntityType(UdiType.ClosedGuid, "macro");
            public static UdiEntityType Template = new UdiEntityType(UdiType.ClosedGuid, "template");
            public static UdiEntityType DocumentType = new UdiEntityType(UdiType.ClosedGuid, "document-type");
            public static UdiEntityType DocumentTypeContainer = new UdiEntityType(UdiType.ClosedGuid, "document-type-container");
            public static UdiEntityType DocumentTypeBluePrints = new UdiEntityType(UdiType.ClosedGuid, "document-type-blueprints");
            public static UdiEntityType MediaType = new UdiEntityType(UdiType.ClosedGuid, "media-type");
            public static UdiEntityType MediaTypeContainer = new UdiEntityType(UdiType.ClosedGuid, "media-type-container");
            public static UdiEntityType DataType = new UdiEntityType(UdiType.ClosedGuid, "data-type");
            public static UdiEntityType DataTypeContainer = new UdiEntityType(UdiType.ClosedGuid, "data-type-container");
            public static UdiEntityType MemberType = new UdiEntityType(UdiType.ClosedGuid, "member-type");
            public static UdiEntityType MemberGroup = new UdiEntityType(UdiType.ClosedGuid, "member-group");
            public static UdiEntityType RelationType = new UdiEntityType(UdiType.ClosedGuid, "relation-type");

            // FORMS
            public static UdiEntityType FormsForm = new UdiEntityType(UdiType.ClosedGuid, "forms-form");
            public static UdiEntityType FormsPreValue = new UdiEntityType(UdiType.ClosedGuid, "forms-prevalue");
            public static UdiEntityType FormsDataSource = new UdiEntityType(UdiType.ClosedGuid, "forms-datasource");

            // STRING
            public static UdiEntityType Language = new UdiEntityType(UdiType.ClosedString, "language");
            public static UdiEntityType MacroScript = new UdiEntityType(UdiType.ClosedString, "macroscript");
            public static UdiEntityType MediaFile = new UdiEntityType(UdiType.ClosedString, "media-file");
            public static UdiEntityType TemplateFile = new UdiEntityType(UdiType.ClosedString, "template-file");
            public static UdiEntityType Script = new UdiEntityType(UdiType.ClosedString, "script");
            public static UdiEntityType Stylesheet = new UdiEntityType(UdiType.ClosedString, "stylesheet");
            public static UdiEntityType PartialView = new UdiEntityType(UdiType.ClosedString, "partial-view");
            public static UdiEntityType PartialViewMacro = new UdiEntityType(UdiType.ClosedString, "partial-view-macro");
        }
    }
}
